package Backend.ApiArquivos;

public enum Bairros {
    AGUA_RASA("Água Rasa", "Zona Leste"),
    ALTO_DE_PINHEIROS("Alto de Pinheiros", "Zona Oeste"),
    AMERICANOPOLIS("Americanópolis", "Zona Sul"),
    ARICANDUVA("Aricanduva", "Zona Leste"),
    ARTUR_ALVIM("Artur Alvim", "Zona Leste"),
    BELA_VISTA("Bela Vista", "Centro"),
    BELENZINHO("Belenzinho", "Zona Leste"),
    BOM_RETIRO("Bom Retiro", "Centro"),
    BRASILANDIA("Brasilândia", "Zona Norte"),
    BRAS("Brás", "Centro"),
    CACHOEIRINHA("Cachoeirinha", "Zona Norte"),
    CAMBUCI("Cambuci", "Zona Sul"),
    CAMPO_BELO("Campo Belo", "Zona Sul"),
    CAMPO_GRANDE("Campo Grande", "Zona Sul"),
    CAMPO_LIMPO("Campo Limpo", "Zona Sul"),
    CAPAO_REDONDO("Capão Redondo", "Zona Sul"),
    CARRAO("Carrão", "Zona Leste"),
    CASA_VERDE("Casa Verde", "Zona Norte"),
    CERQUEIRA_CESAR("Cerqueira César", "Centro"),
    CIDADE_DUTRA("Cidade Dutra", "Zona Sul"),
    CIDADE_LIDER("Cidade Líder", "Zona Leste"),
    CIDADE_TIRADENTES("Cidade Tiradentes", "Zona Leste"),
    CONSOLACAO("Consolação", "Centro"),
    CURSINO("Cursino", "Zona Sul"),
    ERMELINO_MATARAZZO("Ermelino Matarazzo", "Zona Leste"),
    FREGUESIA_DO_O("Freguesia do Ó", "Zona Norte"),
    FAZENDA_CANGACU("Fazenda Cangaçu", "Zona Sul"),
    GRAJAU("Grajaú", "Zona Sul"),
    GUAIANASES("Guaianases", "Zona Leste"),
    HIGIENOPOLIS("Higienópolis", "Centro"),
    IGUATEMI("Iguatemi", "Zona Sul"),
    INDIANOPOLIS("Indianópolis", "Zona Sul"),
    INTERLAGOS("Interlagos", "Zona Sul"),
    IPIRANGA("Ipiranga", "Zona Sul"),
    ITAIM_BIBI("Itaim Bibi", "Zona Sul"),
    ITAIM_PAULISTA("Itaim Paulista", "Zona Leste"),
    ITAQUERA("Itaquera", "Zona Leste"),
    JABAQUARA("Jabaquara", "Zona Sul"),
    JACANA("Jaçanã", "Zona Norte"),
    JARAGUA("Jaraguá", "Zona Norte"),
    JARDIM_ANGELA("Jardim Ângela", "Zona Sul"),
    JARDIM_CAPELA("Jardim Capela", "Zona Sul"),
    JARDIM_DOS_ESTADOS("Jardim dos Estados", "Zona Oeste"),
    JARDIM_EUROPA("Jardim Europa", "Zona Oeste"),
    JARDIM_GUARANI("Jardim Guarani", "Zona Oeste"),
    JARDIM_HELENA("Jardim Helena", "Zona Leste"),
    JARDIM_PAULISTA("Jardim Paulista", "Zona Sul"),
    JARDIM_SAO_LUIS("Jardim São Luís", "Zona Oeste"),
    JOSE_BONIFACIO("José Bonifácio", "Zona Leste"),
    LAJEADO("Lajeado", "Zona Leste"),
    LAPA("Lapa", "Zona Oeste"),
    LIBERDADE("Liberdade", "Centro"),
    LIMAO("Limão", "Zona Norte"),
    LUZ("Luz", "Centro"),
    M_BOI_MIRIM("M'Boi Mirim", "Zona Sul"),
    MOEMA("Moema", "Zona Sul"),
    MOOCA("Mooca", "Zona Leste"),
    MORUMBI("Morumbi", "Zona Oeste"),
    PARAISO("Paraíso", "Zona Sul"),
    PARELHEIROS("Parelheiros", "Zona Sul"),
    PARI("Pari", "Zona Leste"),
    PARQUE_SAO_JORGE("Parque São Jorge", "Zona Leste"),
    PEDREIRA("Pedreira", "Zona Sul"),
    PENHA("Penha", "Zona Leste"),
    PERDIZES("Perdizes", "Zona Oeste"),
    PINHEIROS("Pinheiros", "Zona Oeste"),
    PONTE_RASA("Ponte Rasa", "Zona Leste"),
    RAPOSO_TAVARES("Raposo Tavares", "Zona Oeste"),
    REPUBLICA("República", "Centro"),
    SACOMA("Sacomã", "Zona Sul"),
    SANTA_CECILIA("Santa Cecília", "Centro"),
    SANTANA("Santana", "Zona Norte"),
    SANTO_AMARO("Santo Amaro", "Zona Sul"),
    SAO_FRANCISCO("São Francisco", "Zona Oeste"),
    SAO_LUCAS("São Lucas", "Zona Leste"),
    SAO_MATEUS("São Mateus", "Zona Leste"),
    SAO_MIGUEL("São Miguel", "Zona Leste"),
    SAO_RAFEL("São Rafael", "Zona Leste"),
    SAPOPEMBA("Sapopemba", "Zona Leste"),
    SE("Sé", "Centro"),
    SOCORRO("Socorro", "Zona Sul"),
    TATUAPE("Tatuapé", "Zona Leste"),
    TERCEIRA_DIVISAO("Terceira Divisão", "Zona Norte"),
    TUCURUVI("Tucuruvi", "Zona Norte"),
    VILA_ANDRADE("Vila Andrade", "Zona Sul"),
    VILA_CURUCA("Vila Curuçá", "Zona Leste"),
    VILA_DIONISIA("Vila Dionísia", "Zona Leste"),
    VILA_ESPERANCA("Vila Esperança", "Zona Leste"),
    VILA_FACHINI("Vila Fachini", "Zona Leste"),
    VILA_FORMOSA("Vila Formosa", "Zona Leste"),
    VILA_GUILHERME("Vila Guilherme", "Zona Norte"),
    VILA_JACUI("Vila Jacuí", "Zona Leste"),
    VILA_LEOPOLDINA("Vila Leopoldina", "Zona Oeste"),
    VILA_MARIA("Vila Maria", "Zona Norte"),
    VILA_MARIANA("Vila Mariana", "Zona Sul"),
    VILA_MATILDE("Vila Matilde", "Zona Leste"),
    VILA_MEDEIROS("Vila Medeiros", "Zona Norte"),
    VILA_PRUDENTE("Vila Prudente", "Zona Leste"),
    VILA_RE("Vila Ré", "Zona Leste"),
    VILA_REGENTE_FEIJO("Vila Regente Feijó", "Zona Leste"),
    VILA_SAO_VICENTE("Vila São Vicente", "Zona Leste"),
    VILA_SONIA("Vila Sônia", "Zona Sul");

    private final String nome;
    private final String zona;

    Bairros(String nome, String zona) {
        this.nome = nome;
        this.zona = zona;
    }

    // Métodos getters
    public String getNome() {
        return nome;
    }

    public String getZona() {
        return zona;
    }
}
